### ISSUE TITLE
Desktop app

### ISSUE THREAD

**Issue by hillelcoren** [VirtualPinballSpreadsheet/vps-db#1]
Hi,

This is a great project!

Is there any interest in having a desktop frontend built for it? I'd be happy to help with it. 

A desktop app would have access to the local file system to check which tables are already downloaded as well as make it easier to add new tables.

**Comment by Kongedam** [comment]
Hi
There is already such an app and it can do even more 😀 

Check it out here https://github.com/syd711/vpin-studio

**Comment by hillelcoren** [comment]
Very cool, thanks! I wasn't aware of it
